name: Auto Merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the PR is from Dependabot
        if: github.actor == 'dependabot[bot]'
        run: |
          echo "Dependabot PR detected"

      - name: Auto-merge Dependabot PR
        if: github.actor == 'dependabot[bot]'
        run: |
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"merge_method":"merge"}' \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge"
